server:
  port: 8888


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
#    feign.hystrix.enabled: true
    service-url:
      defaultZine: http://${eureka.instance.hostname}:${server.port}/eureka/